### ISSUE TITLE
Huge deformation in bspline transformation

### ISSUE THREAD

**Issue by pmgautam** [biomedia-mira/istn#10]
I was running the code on provided 2d data in affine and bspline mode. Affine transformation seems to preserve structure. However in Bspline, deformation is huge and the image structure is also not maintained. Training was done without changing any parameter from the repo.
Original image
![original_image](https://user-images.githubusercontent.com/28428143/103559697-a7cf0280-4ede-11eb-88cb-9c71a7914e29.png)

Warped image
![warped_image](https://user-images.githubusercontent.com/28428143/103559702-aac9f300-4ede-11eb-99e1-662dae571a30.png)

What could be the reason behind such deformation? I compared the bspline code with airlab and looks like diffeomorphism and Diffusion Regulariser are not added. I was hoping adding them might make the deformation look reasonable. Is there anything else that needs to be taken care of.

Thank you for the help.

**Comment by bglocker** [comment]
Yeah, I am not sure we ever tested the 2D B-splines on this synthetic data which was specifically constructed as a demonstration example for the concept of structure-guided registration.

You could try to increase the control point spacing, as the default setting might not be great.

My general advice would be to opt for a different transformation model than B-splines. We have recently used SVFs within learning based image registration which gives much better results.

**Comment by pmgautam** [comment]
Thank you very much for the response. Can you please refer me to the papers that might be useful?

**Comment by bglocker** [comment]
We have been recently working on an extension of the ISTN framework, and the pre-print is available [here](https://arxiv.org/abs/2012.10533)

I would also suggest to check out the [airlab library](https://github.com/airlab-unibas/airlab)  and [voxelmorph ](https://github.com/voxelmorph/voxelmorph)
