### ISSUE TITLE
Implementation of Atlas-ISTN

### ISSUE THREAD

**Issue by Pratyma** [biomedia-mira/istn#11]
Hi. It is, actually, not an issue related to the ISTN code. I want to know if you have any plan to release the code in Github for your paper-"Atlas-ISTN: Joint Segmentation, Registration and Atlas Construction with Image-and-Spatial Transformer Networks."

**Comment by bglocker** [comment]
Thanks for your interest. We are looking into this and will hopefully be able to release the code for Atlas-ISTNs very soon.

**Comment by Pratyma** [comment]
Hi, Ben. It has been more than a year. Have you decided to release the code for Atlas-ISTN now? Or have you already released it, and it was me who did not find it. I really wanted to implement your method for my datasets.

**Comment by bglocker** [comment]
Hi, yes, this is going to be released very soon. Note [the paper was only published a few weeks](https://www.sciencedirect.com/science/article/pii/S1361841522000354), ago. We are currently preparing the code release.

**Comment by Pratyma** [comment]
First of all, **Congratulations** on getting your work published in Medical Image Analysis Journal. And thank you for deciding to make your code public.

**Comment by 25benjaminli** [comment]
@bglocker Has the code release been prepared for the ATLAS-ISTN study? If so, where can I find it? Thanks.

**Comment by bglocker** [comment]
Atlas-ISTN code is available here: [https://github.com/biomedia-mira/atlas-istn](https://github.com/biomedia-mira/atlas-istn)
