### ISSUE TITLE
Issue with 3D transformation

### ISSUE THREAD

**Issue by samz00** [biomedia-mira/istn#15]
I was running code with Brain MRI functional images with no segmentations and masks. I was wondering if the STN layer only controls the rotation of the image. Since I don't use the segmentation data, ITN provides me a bad result as I attached.
![image](https://user-images.githubusercontent.com/43385583/124203856-a3f5f480-daab-11eb-81fb-1369f81be6ed.png)

**Comment by bglocker** [comment]
Hi, thanks for trying out ISTNs for your task. If there are no segmentations (or other types of annotations) being provided during training, ISTNs might not be the most useful approach. The ITN relies on some annotations for training, and without it wouldn't be able to generate useful images for the STN.

**Comment by samz00** [comment]
I wonder what kinds of segmentation data you use for training. I have used segmentation data like this:
![image](https://user-images.githubusercontent.com/43385583/126053341-34d5bdbb-44a1-4d60-8a66-6daf59a30a2d.png)
and the ITN result still looks very bad:
![image](https://user-images.githubusercontent.com/43385583/126053353-bd3ba584-ec1d-4483-980a-23e0965f9e4e.png)
