### ISSUE TITLE
requirements.txt has line that freezes pip3

### ISSUE THREAD

**Issue by YahiyaHussain** [biomedia-mira/istn#2]
pip install -r requirements.txt won't run unless I remove pkg-resources=0.0.0 from file. https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command According to this link this line being added to the requirements.txt is a bug from pip3 providing incorrect metadata to pip.

**Comment by mauinz** [comment]
Thanks for letting us know. we hadn't had issues with this before so we'll run some checks before making changes.

If you could you provide us with some more details of your set up that would be great.
