### ISSUE TITLE
The Affine matrix scale

### ISSUE THREAD

**Issue by zhirui-gao** [biomedia-mira/istn#20]
Great job,and I have a question. 
In code [Line 70](https://github.com/biomedia-mira/istn/blob/6bbf6ebff35643917a33a15e8f964371b24077ad/pymira/nets/stn.py#L70)
Is the **parameter 0.1** to control the translation amount in a small range?
Looking forward your reply!
Best wishes!

**Comment by bglocker** [comment]
The translation is relative to the image size. Here, 0.1 refers to a maximum translation of 10% of the image dimensions (the internal warp function assumes the image to have size 1.0).

**Comment by zhirui-gao** [comment]
Thanks for your early reply!
