### ISSUE TITLE
Request for ISTN Code Version Used in Learn2Reg LungCT Challenge

### ISSUE THREAD

**Issue by YutaZhuo** [biomedia-mira/istn#26]
I noted that the research participated in the Learn2Reg LungCT challenge in 2021. I observed that its performance is still ranked highly on today's LeaderBoard.
However, when attempting to replicate the results with the open-source code on the LungCT dataset, the outcomes are significantly different.
I would be grateful if you could share the version of the code that was utilized during the Learn2Reg challenge.

**Comment by bglocker** [comment]
I believe the challenge entry was based on the implementation of our follow-up work on Atlas-ISTNs. Please check out this code repository here: https://github.com/biomedia-mira/atlas-istn
