### ISSUE TITLE
Able to run 2D Synthetic Examples but not 3D

### ISSUE THREAD

**Issue by YahiyaHussain** [biomedia-mira/istn#4]
Hello,

I am working on a Ubuntu linux subsystem for windows. I have installed all the requirements from the requirements folder and have successfully run all the 2D examples written in the comments of istn-reg.py and gotten the plot of the output validation curves and training curves.  However I cannot run the 3D examples code:

python istn-reg.py --mode3d --loss i --out output3d/istn-i --model output3d/istn-i/train/model --config data/brain3d/config.affine.json --train data/brain3d/train.csv --train_seg data/brain3d/train.seg.csv --train_msk data/brain3d/train.msk.csv --val data/brain3d/val.csv --val_seg data/brain3d/val.seg.csv --val_msk data/brain3d/val.msk.csv --test data/brain3d/test.csv --test_seg data/brain3d/test.seg.csv --test_msk data/brain3d/test.msk.csv

I get this error:

...
----------------------------------------
TRAINING data...
----------------------------------------
Reading source image <source>.nii.gz
Traceback (most recent call last):
  File "istn-reg.py", line 487, in <module>
    train(args)
  File "istn-reg.py", line 251, in train
    resampler_seg=config.resampler_seg)
  File "/home/yahtzee/istn/pymira/img/datasets.py", line 122, in __init__
    source = sitk.ReadImage(src_path, sitk.sitkFloat32)
  File "/home/yahtzee/.local/lib/python3.6/site-packages/SimpleITK/SimpleITK.py", line 8876, in ReadImage
    return _SimpleITK.ReadImage(*args)
RuntimeError: Exception thrown in SimpleITK ReadImage: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:99:
sitk::ERROR: The file "<source>.nii.gz" does not exist.

I am I doing something wrong? am I missing a dependency or anything?

Thank you

**Comment by mauinz** [comment]
Hi, 

Thanks for showing an interest in our work!

Seems like you're trying to use our example command line call to run the 3D case. Unfortunately we can't provide the 3D data so the example isn't a working one. We haven't actually provided the data or the CSV which lists the data to be used. You'll need to generate your own 3D data and the corresponding CSV files to point to it. 

Let me know if I can close this issue.

**Comment by mauinz** [comment]
I'll close this issue due to inactivity.
