### ISSUE TITLE
Rogue indentation causes exception

### ISSUE THREAD

**Issue by jrubin01** [biomedia-mira/istn#5]
Trying to run:

`python istn-reg.py --mode3d --loss i --out output3d/istn-i --model output3d/istn-i/train/model --config data/synth3d/config.json --train data/synth3d/train.csv --train_seg data/synth3d/train.seg.csv --val data/synth3d/val.csv --val_seg data/synth3d/val.seg.csv`

There is an indentation error on line 180 in pymira/nets/stn.py that will cause running the script to fail, giving: 

```
Traceback (most recent call last):
  File "istn-reg.py", line 39, in <module>
    from pymira.nets.stn import STN2D, BSplineSTN2D, STN3D, BSplineSTN3D
  File "/local/home/Jonathan/istn/pymira/nets/stn.py", line 180
    self.fc.weight.data.zero_()
                              ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by jrubin01** [comment]
Also, a similar error on line 506 in pymira/nets/stn.py

**Comment by bglocker** [comment]
Thanks for spotting. This should be resolved now with the latest commit. I've removed the initialization altogether, as it didn't seem to work very well anyhow. Default initialization seems better for training.
