### ISSUE TITLE
BSpline transformation clarification

### ISSUE THREAD

**Issue by pmgautam** [biomedia-mira/istn#9]
I've been using the BSpline3D network. When I try to use the predicted parameters in SimpleITK, the transformation result do not match. STN network heavily warps the images while in SimpleITK they seem as not being warped. Can anyone help me with the reasoning of such behaviour.

**Comment by bglocker** [comment]
I'm afraid the BSpline STN used here and the BSplines transformation model in SimpleITK are somewhat different and one cannot directly relate the transformation parameters that are predicted by the STN with the parameters of the SimpleITK model.

**Comment by prameshgautam** [comment]
In that case, can we find the points that will be deformed into after applying BSplineSTN. I would like to compute `(x', y', z')` for (`x, y, z)` after warping the image using BSplineSTN warp method.
